name: alchemy_web3
description: An Alchemy Platform client for Flutter & Dart
version: 0.2.0
homepage: https://github.com/oliverbytes/alchemy_web3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  logger: ^2.4.0
  decimal: ^3.0.2
  either_dart: ^1.0.0
  # NETWORK
  dio: ^5.6.0
  json_rpc_2: ^3.0.2
  web_socket_channel: ^3.0.1
  # CRYPTO
  pointycastle: ^3.9.1
  convert: ^3.1.1
  # WEB3
  web3dart: ^2.7.3


dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
